# Generated by Django 5.2.11 on 2026-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
